### ISSUE TITLE
Deprecate this driver

### ISSUE THREAD

**Issue by raquelxmoss** [cyclejs-community/cycle-mouse-driver#14]
Hey folks. Here's the good news: Cycle DOM now supports selecting `document` and `body`. Awesome! Users can now do things like:

`DOM.select('document').events('mouseup');`

Since this is now supported, we don't need to use a driver to do this.

What shall we do with Cycle Mouse Driver? Keep it, or deprecate it?

My preference would be to deprecate it, and encourage users to go ahead and use the new DOM feature.

Does anyone see a reason not to deprecate this driver?

**Comment by artfuldev** [comment]
+1 for deprecate

**Comment by raquelxmoss** [comment]
Deprecated 😄

**Comment by farism** [comment]
It might be good to publish a new version on npm so that the deprecation notice shows up there

**Comment by raquelxmoss** [comment]
@farism I thought that I had, but clearly not! I'll do it tonight when I'm on my home computer. Thanks for letting me know.
