### ISSUE TITLE
Add a function for positions relative to an element

### ISSUE THREAD

**Issue by Widdershin** [cyclejs-community/cycle-mouse-driver#2]
For example, `relativePositions (element$): position$`.

**Comment by artfuldev** [comment]
`realtivePosition(selector: string | element$: Stream<HTMLElement>): Stream<position>`

**Comment by raquelxmoss** [comment]
What about `Mouse.relativeTo('.selector')`?

Takes in a selector and a 'starting point' e.g. `Mouse.relativeTo('.selector', 'topRight')`
Returns a stream of objects that contain a `position` as a vector, and an `isOverElement` boolean

**Comment by raquelxmoss** [comment]
What about `Mouse.relativeTo('.selector')`?

Takes in a selector and a 'starting point' e.g. `Mouse.relativeTo('.selector', 'topRight')`. `startingPoint` (better name suggestions welcome) would be an optional argument. If not specified, the starting point will be `topLeft`.

Starting points:
`topLeft`
`topCenter`
`topRight`
`middleLeft`
`middleCenter`
`middleRight`
`bottomLeft`
`bottomCenter`
`bottomRight`

Returns a stream of objects that contain a `position` as a vector, and an `isOverElement` boolean.

``` js
{
  position: {x: -20, y: 50},
  isOverElement: false
}
```
