### ISSUE TITLE
Add all MouseEvents

### ISSUE THREAD

**Issue by artfuldev** [cyclejs-community/cycle-mouse-driver#3]
We could start with this as a reference:
http://javascript.info/tutorial/mouse-events

SImple Events:
- [x] mousedown
- [x] mouseup
- [ ] mouseover
- [ ] mouseout
- [ ] mousemove

Complex Events:
- [x] click
- [ ] contextmenu
- [ ] dblclick
  
  We could also expose some more functionality, like the driver making a few events cross-platform.

**Comment by raquelxmoss** [comment]
I have added mouseup, mousedown, and click 😸

**Comment by artfuldev** [comment]
Can we use the `ups()`, `downs()` and `clicks()` API?
The API looks inconsistent, with `positions()`, but `click()` where both are streams.

BTW you need to add me as a contributor :)

**Comment by raquelxmoss** [comment]
To be honest, I was thinking about it, and I prefer the `up()`, `down()`, `click()` style, and I think I would actually prefer that for Cycle Keyboard as well. I went with the names that I have generally been using in my own work, and my pattern has been to name streams as singular, with Finnish notation: `event$`, unless I am dealing with a stream-of-streams situation (thankfully, we aren't here 😄 . If anything, I would maybe change `positions()` to be singular like the others, but I'll wait for the next release.

I'm open to more opinions on this, so if any other users and contributors have ideas on this, please let us know!

**Comment by artfuldev** [comment]
@cyclejs-community/contributors anything?

**Comment by Widdershin** [comment]
Can we please refrain from tagging cyclejs-community/contributors unless it's a discussion about the community as a whole?

If you like I can set up a team for the people who are contributing to this project so you can more easily get their attention.

**Comment by artfuldev** [comment]
@raquelxmoss `up$`, `click$` is great, like the keyboard driver had a `keyUp$`, it conveys meaning clearly. But when we use a function, it generally reads what it returns, and what it returns here is not a single `up`, but several `ups` as a stream. Just my 2 cents.

@Widdershin point taken. I was inviting people to contribute, will refrain from this.

**Comment by artfuldev** [comment]
@raquelxmoss which is also why the `@cycle/dom` driver has `events()` and `elements()` methods

**Comment by FeliciousX** [comment]
would it also make sense if we can make use of the function like `up( <selector> )` to filter the streams? or is it better handled by just filtering manually?

**Comment by artfuldev** [comment]
We will have selectors to filter the streams... I think... That's how cycle-keyboard does it...

**Comment by raquelxmoss** [comment]
@FeliciousX So usually I just do this with `DOM.select`, and I use the mouse driver to worry about events on document, rather than events within my cycle app.  I did think about adding a filter, so that all mouse events can be dealt with in the Mouse driver, and so that you can deal with events on elements that might be outside of your cycle app as well. If y'all think that's a good idea, I'd like to add that enhancement.

**Comment by FeliciousX** [comment]
@raquelxmoss since a driver is to communicate anything `outside` of cycle app, I think adding a filter will help with that when people are working with a cycle app hybrid :D 

I do think it's a good idea

**Comment by artfuldev** [comment]
Oh, sorry. cycle-keyboard doesn't. It exists only to interface directly with the keyboard, so no DOM-specific things. Maybe they are better suited for the DOM Driver?

**Comment by raquelxmoss** [comment]
@FeliciousX Cool, yeah I was thinking along the same lines, but sorta wanted to wait for more confirmation/people expressing a need before going ahead with that. I haven't plonked a Cycle app inside another app before, but I feel like that would be interesting, and so I definitely see the use case.
